server:
  port: 9090
  
spring:
  datasource:
    url: jdbc:mysql://192.168.0.214:3306/study?characterEncoding=UTF-8
    username: shiyq
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect